### PR TITLE
Standardize on swagger_doc naming

### LINKED ISSUE #43: swagger_doc tag doesn't work
As [comments](https://github.com/drewish/rspec-rails-swagger/blob/5e6127c08f2a4e362204a525267e02b5ad5ebad2/spec/swagger_helper.rb#L16) or [rswag](https://github.com/domaindrivendev/rswag#global-metadata) (rspec-rails-swagger based on rswag):

>   By default, the operations defined in spec files are added to the first document below. You can override this behavior by adding a `swagger_doc` tag to the the root example_group in your specs, e.g.

```ruby
describe '...', swagger_doc: 'v2/swagger.json'
```

But it doesn't work if I used it with RSpec, like below:
```ruby
RSpec.describe 'mock allocation summary', type: :request, swagger_doc: 'v2/swagger.yml' do
...
    path '/post' do
...
end
```

Is there anybody have some idea?

### PR DESCRIPTION
**Pull request by drewish**
Fixes #43 by allowing the document to be specified in a parent context. 

In the process changes the `swagger_document` name to `swagger_doc` to match the name used in the configuration file.

### CODE REVIEW

**Comment by drewish** [comment]
Waiting on https://www.traviscistatus.com/incidents/lxq2zxskjyf1 to be resolved before merging this.

File: lib/rspec/rails/swagger/helpers.rb [hunk 1]
```diff
@@ -45,7 +45,7 @@ def path template, attributes = {}, &block
             #TODO template might be a $ref
             meta = {
               swagger_object: :path_item,
-              swagger_document: attributes[:swagger_document] || RSpec.configuration.swagger_docs.keys.first,
+              swagger_document: attributes[:swagger_document] || default_document,
```
Comment (zddhub) [inline lib/rspec/rails/swagger/helpers.rb]: Great work! 🥇 

Would you like to use `swagger_doc` instead of `swagger_document` to align with rswag? or add usage in readme is good thing as well 👍

Comment (drewish) [reply lib/rspec/rails/swagger/helpers.rb]: I think I'll keep the current naming just because it's currently getting past to child contexts that way and it'd be a little weird having two different names for it. Adding to the docs is a good idea though.

Comment (drewish) [reply lib/rspec/rails/swagger/helpers.rb]: Ah seeing what you're saying in #43 about https://github.com/drewish/rspec-rails-swagger/blob/5e6127c08f2a4e362204a525267e02b5ad5ebad2/spec/swagger_helper.rb#L16 
and the config using the `swagger_docs` name... it would make sense to pick one. I think it makes sense to change that and then bump the version to indicate the compatibility break.

Comment (zddhub) [reply lib/rspec/rails/swagger/helpers.rb]: It's pretty great work! Thanks @drewish. 👍 👍 👍, You made my life easy. Hope it would be released soon. 🎉🎉🎉
